#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('New Laravel Project Installer', '1.0.0');
$app->add(new Permafrost\NewLaravelProject\Console\CreateCommand);

$app->run();